name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: ./gradlew build javadoc
      run: ./gradlew build
    - name: ./gradlew requireJavadoc
      run: ./gradlew requireJavadoc
    - name: clone plume-scripts
      run: git clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git
    - name: git-clone-related checker-framework
      run: ./git-clone-related /tmp/"$USER"/plume-scripts/git-clone-related typetools checker-framework
    - name: CF inference tests
      run: cd ../checker-framework && ./gradlew inferenceTests

